# install and cache app dependencies
FROM node:10-alpine as builder
COPY package.json package-lock.json ./
RUN npm install --only=prod&& mkdir /client && mv ./node_modules ./client
WORKDIR /client
COPY . .
RUN npm run build
# ------------------------------------------------------
# Production Build
# ------------------------------------------------------
FROM nginx:1.16.0-alpine
COPY --from=builder /client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
