version: '3.3'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development