version: "3.3"
services:
    express:
        build:
            context: ./express
        ports:
            - "9000:9000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"